version: '3.0'
services:
  mf-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085

  mobilitydb:
    image: mobilitydb/mobilitydb:latest
    container_name: mobilitydb
    ports:
      - 25432:5432
    environment:
      - POSTGRES_DB=mobilitydb
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

    restart: on-failure